name: morse_learn
description: "A morse learning app."

publish_to: "none"

version: 2.0.1+3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.6
  share_plus: 8.0.3
  shared_preferences: 2.2.3
  vibration: 1.8.4
  intl: 0.18.1
  flutter_animate: 4.5.0
  provider: 6.1.2
  package_info_plus: 7.0.0
  just_audio: 0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  dependency_validator: 3.2.3
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
